const bool TESTMODE = false;
const float THRESHOLD = 1;
const float TUNERATE = 1;
const int TIMEOUT = 4000;
const int LATERAL = 0;
const int ANGULAR = 1;
const int IDLE = 2000;
const int LOAD = 4800;
const int FAR = 22800;
const int DIGITAL = 0;
const int MOTOR = 1;
const int BLUE = -1;
const int RED = 1;
const int VAR = 2;

int lastSecondStageVoltage = 0;
int lastFirstStageVoltage = 0;
int movementStartTime = 0;
int ladybrown_target = 0;
int currentScreen = 0;
int coordLogItem = 0;
int movementTime = 0;
int colorReading = 0;
int lastRightX = 0;
int allyColor = 0;
int lastLeftY = 0;
int holdCount = 0;
int lastWrite = 0;
int tuneType = 0;
int spintake = 0;
int movement = 0;
int autoNum = 0;
int rightX;
int leftY;

bool movementStarted = false;
bool lastScoreState = false;
bool lastRightDoink = false;
bool lastIntakeLift = false;
bool lastLoadState = false;
bool lastLeftDoink = false;
bool autoRunning = false;
bool scoreState = false;
bool lastClamp = false;
bool loadState = false;
bool recording = false;
bool selecting = true;
bool fileOpen = false;

std::list<std::string> coordLog;
FILE* recordings = nullptr;
std::string coordLogEntry;
